=== Jazeera92/wba2/Phase1/src/Aufgabe3c.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Rezepte">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Rezept">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Titel"/>
              <xs:element type="xs:string" name="Beschreibung"/>
              <xs:element name="Bilder">
                <xs:complexType>
                  <xs:sequence>
                  	<xs:element name="Bild" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                      	<xs:sequence>
                    		<xs:element type="xs:byte" name="Nummer"/>
                    		<xs:element type="xs:string" name="Quelle"/>
                    		<xs:element type="xs:string" name="Titel"/>
                    	</xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Zutaten">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Zutat" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Menge"/>
                          <xs:element type="xs:string" name="Einheit"/>
                          <xs:element type="xs:string" name="Name"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="portion_id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Zubereitung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Arbeitszeit">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="Einheit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Schwierigkeitsgrad"/>
                    <xs:element name="Brennwert">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="Einheit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Text"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Kommentare">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Titel"/>
                    <xs:element name="Kommentar">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Nutzer"/>
                          <xs:element type="xs:string" name="Avatar"/>
                          <xs:element name="Zeitstempel">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:byte" name="Tag"/>
                                <xs:element type="xs:byte" name="Monat"/>
                                <xs:element type="xs:short" name="Jahr"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="Text"/>
                          <xs:element type="xs:string" name="Hilfreich"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jazeera92/wba2/Phase1/src/Aufgabe3d(2).xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3c.xsd">
  <Rezept rezept_id="1">
    <Titel>Friedhelms Hähnchenschenkel</Titel>
    <Beschreibung>mit Kartoffeln, Lauchzwiebeln und Zucchini</Beschreibung>
    <Bilder>
      <Bild>
        <Nummer>15</Nummer>
        <Quelle>img/pic.png</Quelle>
        <Titel>Foto von Mammapia</Titel>
      </Bild>
    </Bilder>
    <Zutaten portion_id="4">
      <Zutat>
        <Menge>4</Menge>
        <Einheit>große</Einheit>
        <Name>Hähnchenschenkel</Name>
      </Zutat>
      <Zutat>
        <Menge>1.5</Menge>
        <Einheit>kg</Einheit>
        <Name>Kartoffel(n), vorwiegend festkochend</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>Bund</Einheit>
        <Name>Lauchzwiebel(n)</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit></Einheit>
        <Name>Zwiebeln</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit></Einheit>
        <Name>Knoblauchzehe(n)</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>große</Einheit>
        <Name>Zucchini</Name>
      </Zutat>
      <Zutat>
        <Menge>3</Menge>
        <Einheit></Einheit>
        <Name>Paprikaschote(n), greöstet</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL, gehäuft</Einheit>
        <Name>Rosmarin</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL, gestr.</Einheit>
        <Name>Thymian</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Olivenöl</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Gewürzmischung (Hähnchen-Gewürzsalz)</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL</Einheit>
        <Name>Salz</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Olivenöl</Name>
      </Zutat>
    </Zutaten>
    <Zubereitung>
      <Arbeitszeit>20
        <Einheit>Min</Einheit>
      </Arbeitszeit>
      <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
      <Brennwert>
        <Einheit>Keine Angabe</Einheit>
      </Brennwert>
      <Text><![CDATA[Die Kartoffeln schälen, waschen und vierteln oder achteln, 10 Minuten in Salzwasser kochen. Hähnchenschenkel mit dem Gewürzsalz bestreuen. 
					Backofen auf 200° Grad vorheizen.
					Aus gehacktem Knoblauch, Salz, Paprikapulver, Pfeffer, Rosmarin, Thymian und Olivenöl eine Marinade herstellen und die Hähnchenschenkel damit einstreichen. 
					Die abgegossenen Kartoffeln in einer Auflaufform mit der restlichen Marinade übergießen und mischen. Die Hähnchenschenkel auf die Kartoffeln legen und im Backofen 40 Minuten backen.
					Während die Hähnchenschenkel im Backofen schmoren, die Lauchzwiebeln, Zucchini und Paprikaschoten in Stücke schneiden, nach Ende der Garzeit mit den Kartoffeln mischen und alles für weitere 20 Minuten in den Backofen geben.]]></Text>
    </Zubereitung>
    <Kommentare>
      <Titel>Kommentare anderer Nutzer</Titel>
      <Kommentar kommentar_id="1">
        <Nutzer>Senseless</Nutzer>
        <Avatar>img/avatar.png</Avatar>
        <Zeitstempel>
          <Tag>4</Tag>
          <Monat>11</Monat>
          <Jahr>2008</Jahr>
        </Zeitstempel>
        <Text><![CDATA[Hallo, 
				Wahr sehr sehr lecker !!! 
				Lg Sonja ]]></Text>
        <Hilfreich>Hilfreich</Hilfreich>
      </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>

=== Jazeera92/wba2/Phase1/src/Aufgabe3d.xml
<?xml version="1.0" encoding="utf-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3c.xsd">
  <Rezept>
    <Titel>Nußecken</Titel>
    <Beschreibung>str1234</Beschreibung>
    <Bilder>
      <Bild>
        <Nummer>150</Nummer>
        <Quelle>img/cake.jpg</Quelle>
        <Titel>Foto von Schokoliebe </Titel>
      </Bild>
    </Bilder>
    <Zutaten portion_id="32">
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit></Einheit>
        <Name>Eier</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL</Einheit>
        <Name>Backpulver</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Für den Belag</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Aprokosenkonfitüre</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit>Pkt.</Einheit>
        <Name>Vanillezucker</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gemahlen</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gehackt</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Wasser</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Kuchenglasur, Schokolade</Name>
      </Zutat>
    </Zutaten>
    <Zubereitung>
      <Arbeitszeit>
        <Einheit>str1234</Einheit>
      </Arbeitszeit>
      <Schwierigkeitsgrad>str1234</Schwierigkeitsgrad>
      <Brennwert>
        <Einheit>str1234</Einheit>
      </Brennwert>
      <Text>str1234</Text>
    </Zubereitung>
    <Kommentare>
      <Titel>str1234</Titel>
      <Kommentar>
        <Nutzer>str1234</Nutzer>
        <Avatar>str1234</Avatar>
        <Zeitstempel>
          <Tag>12</Tag>
          <Monat>12</Monat>
          <Jahr>2012</Jahr>
        </Zeitstempel>
        <Text>str1234</Text>
        <Hilfreich>str1234</Hilfreich>
      </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>

=== Jazeera92/wba2/Phase1/src/Aufgabe3a.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3c.xsd">
	<Rezept rezept_id="1">
		<Titel>Lenchen’s Schokoladenkuchen</Titel>
		<Beschreibung></Beschreibung>
		<Bilder>
			<Bild>
               	<Nummer>1</Nummer> 
               	<Quelle>img/kuchen.png</Quelle>
                <Titel>Foto von mrsasterix</Titel>
            </Bild>
        </Bilder>
		<Zutaten portion_id="16">
			<Zutat>
				<Menge>200</Menge>
				<Einheit>g</Einheit>
				<Name>Butter</Name>
			</Zutat>
			<Zutat>
				<Menge>200</Menge>
				<Einheit>g</Einheit>
				<Name>Zucker</Name>
			</Zutat>
			<Zutat>
				<Menge>200</Menge>
				<Einheit>g</Einheit>
				<Name>Schokolade</Name>
			</Zutat>
			<Zutat>
				<Menge>120</Menge>
				<Einheit>g</Einheit>
				<Name>Mehl</Name>
			</Zutat>
			<Zutat>
				<Menge>0.5</Menge>
				<Einheit>TL</Einheit>
				<Name>Backpulver</Name>
			</Zutat>
			<Zutat>
				<Menge>1</Menge>
				<Einheit>Pkt.</Einheit>
				<Name>Vanillezucker</Name>
			</Zutat>
			<Zutat>
				<Menge>4</Menge>
				<Einheit></Einheit>
				<Name>Ei(er)</Name>
			</Zutat>
		</Zutaten>
		<Zubereitung>
			<Arbeitszeit>ca. 1<Einheit>Std</Einheit></Arbeitszeit>
			<Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
			<Brennwert>295<Einheit>kcal</Einheit></Brennwert>
			<Text><![CDATA[Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen und mischen. Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben. In eine gut gefettete Form geben. 
						   Bei 180°Grad 40 – 50 Minuten backen.]]>
			</Text>
		</Zubereitung>
		<Kommentare>
			<Titel>Kommentare anderer Nutzer</Titel>
				<Kommentar kommentar_id="1">
					<Nutzer>swieselchen</Nutzer>
					<Avatar>motorad.jpeg</Avatar>
					<Zeitstempel>
						<Tag>07</Tag>
						<Monat>02</Monat>
						<Jahr>2002</Jahr>
					</Zeitstempel>
					<Text>
						<![CDATA[Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade
								 hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben)
								 mein LAG war total begeistert. Ich übrigends auch, super Rezept.]]>
					</Text>
					<Hilfreich>ja</Hilfreich>
				</Kommentar>
		</Kommentare>
	</Rezept>
	<Rezept rezept_id="3">
    <Titel>Nußecken</Titel>
    <Beschreibung></Beschreibung>
    <Bilder>
      <Bild>
        <Nummer>150</Nummer>
        <Quelle>img/cake.jpg</Quelle>
        <Titel>Foto von Schokoliebe </Titel>
      </Bild>
    </Bilder>
    <Zutaten portion_id="32">
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit></Einheit>
        <Name>Eier</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL</Einheit>
        <Name>Backpulver</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Für den Belag</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Aprokosenkonfitüre</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit>Pkt.</Einheit>
        <Name>Vanillezucker</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gemahlen</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gehackt</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Wasser</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Kuchenglasur, Schokolade</Name>
      </Zutat>
    </Zutaten>
    <Zubereitung>
      <Arbeitszeit>45
        <Einheit>Min</Einheit>
      </Arbeitszeit>
      <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
      <Brennwert>
        <Einheit></Einheit>
      </Brennwert>
      <Text><![CDATA[]]></Text>
    </Zubereitung>
    <Kommentare>
      <Titel>Kommentare anderer Nutzer</Titel>
      <Kommentar kommentar_id="1">
        <Nutzer>wellness-line</Nutzer>
        <Avatar>img/profilbild.png</Avatar>
        <Zeitstempel>
          <Tag>12</Tag>
          <Monat>12</Monat>
          <Jahr>2012</Jahr>
        </Zeitstempel>
        <Text><![CDATA[Ein absoluter Volltreffer! Ich verstehe gar nicht, warum bisher noch keine Kommentare dazu abgegeben wurden. 
		Mit diesem Rezept legt man alle Ehre ein - auch immer gut als Geschenk in einer schönen Dose .... 
		Nachbacken lohnt sich garantiert! Schmecken hervorragend. 
		Mein Tipp: Ich nehme ein ganzes Glas Aprikosenmarmelade, werden dann noch saftiger!]]></Text>
        <Hilfreich>ja</Hilfreich>
      </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>
