=== Jazeera92/wba2/Phase1/bin/Aufgabe3c.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="titel">
  <xs:restriction base="xs:string">
	<xs:minLength value="1"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="jahr">
  <xs:restriction base="xs:int">
	<xs:maxExclusive value="2014"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="monat">
  <xs:restriction base="xs:int">
	<xs:minExclusive value="0"/>
	<xs:maxExclusive value="13"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tag">
  <xs:restriction base="xs:int">
	<xs:minExclusive value="0"/>
	<xs:maxExclusive value="32"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="menge">
  <xs:restriction base="xs:float">
	<xs:minExclusive value="0"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="schwierigkeitsgrad">
   <xs:restriction base="xs:string">
     <xs:enumeration value="simple"/>
     <xs:enumeration value="normal"/>
     <xs:enumeration value="pfiffig"/>
   </xs:restriction>
 </xs:simpleType>

  <xs:element name="Rezepte">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Rezept" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>	
              <xs:element type="titel" name="Titel"/>		
              <xs:element type="xs:string" name="Beschreibung"/>
              <xs:element name="Bilder">
                <xs:complexType>
                  <xs:sequence>
                  	<xs:element name="Bild" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                      	<xs:sequence>
                    		<xs:element type="xs:int" name="Nummer"/>
                    		<xs:element type="xs:string" name="Quelle"/>
                    		<xs:element type="xs:string" name="Titel"/>
                    	</xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Zutaten">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Zutat" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="menge" name="Menge"/>
                          <xs:element type="xs:string" name="Einheit"/>
                          <xs:element type="xs:string" name="Name"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="portion_id" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Zubereitung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Arbeitszeit">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="Einheit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="schwierigkeitsgrad" name="Schwierigkeitsgrad"/>
                    <xs:element name="Brennwert">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="Einheit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="Text"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Kommentare">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Titel"/>
                    <xs:element name="Kommentar">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Nutzer"/>
                          <xs:element type="xs:string" name="Avatar"/>
                          <xs:element name="Zeitstempel">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="tag" name="Tag"/>
                                <xs:element type="monat" name="Monat"/>
                                <xs:element type="jahr" name="Jahr"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="Text"/>
                          <xs:element type="xs:string" name="Hilfreich"/>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="kommentar_id" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="rezept_id" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jazeera92/wba2/Phase1/bin/Aufgabe3d.xml
<?xml version="1.0" encoding="utf-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3c.xsd">
  <Rezept rezept_id="3">
    <Titel>Nußecken</Titel>
    <Beschreibung>str1234</Beschreibung>
    <Bilder>
      <Bild>
        <Nummer>150</Nummer>
        <Quelle>img/cake.jpg</Quelle>
        <Titel>Foto von Schokoliebe </Titel>
      </Bild>
    </Bilder>
    <Zutaten portion_id="32">
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>130</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit></Einheit>
        <Name>Eier</Name>
      </Zutat>
      <Zutat>
        <Menge>1</Menge>
        <Einheit>TL</Einheit>
        <Name>Backpulver</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Für den Belag</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Aprokosenkonfitüre</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Butter oder Margarine</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Zucker</Name>
      </Zutat>
      <Zutat>
        <Menge>2</Menge>
        <Einheit>Pkt.</Einheit>
        <Name>Vanillezucker</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gemahlen</Name>
      </Zutat>
      <Zutat>
        <Menge>200</Menge>
        <Einheit>g</Einheit>
        <Name>Haselnüsse,gehackt</Name>
      </Zutat>
      <Zutat>
        <Menge>4</Menge>
        <Einheit>EL</Einheit>
        <Name>Wasser</Name>
      </Zutat>
      <Zutat>
        <Menge></Menge>
        <Einheit></Einheit>
        <Name>Kuchenglasur, Schokolade</Name>
      </Zutat>
    </Zutaten>
    <Zubereitung>
      <Arbeitszeit>45
        <Einheit>Min</Einheit>
      </Arbeitszeit>
      <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
      <Brennwert>
        <Einheit></Einheit>
      </Brennwert>
      <Text><![CDATA[]]></Text>
    </Zubereitung>
    <Kommentare>
      <Titel>Kommentare anderer Nutzer</Titel>
      <Kommentar kommentar_id="1">
        <Nutzer>wellness-line</Nutzer>
        <Avatar>img/profilbild.png</Avatar>
        <Zeitstempel>
          <Tag>12</Tag>
          <Monat>12</Monat>
          <Jahr>2012</Jahr>
        </Zeitstempel>
        <Text><![CDATA[Ein absoluter Volltreffer! Ich verstehe gar nicht, warum bisher noch keine Kommentare dazu abgegeben wurden. 
		Mit diesem Rezept legt man alle Ehre ein - auch immer gut als Geschenk in einer schönen Dose .... 
		Nachbacken lohnt sich garantiert! Schmecken hervorragend. 
		Mein Tipp: Ich nehme ein ganzes Glas Aprikosenmarmelade, werden dann noch saftiger!]]></Text>
        <Hilfreich>ja</Hilfreich>
      </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>

=== Jazeera92/wba2/Phase1/bin/Aufgabe3d(2).xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3c.xsd">
  <Rezept>
    <Titel>Titel</Titel>
    <Beschreibung>Beschreibung</Beschreibung>
    <Bilder>
      <Bild>
        <Nummer>0</Nummer>
        <Quelle>Quelle</Quelle>
        <Titel>Titel</Titel>
      </Bild>
    </Bilder>
    <Zutaten portion_id="0">
      <Zutat>
        <Menge>100</Menge>
        <Einheit>Einheit</Einheit>
        <Name>Name</Name>
      </Zutat>
    </Zutaten>
    <Zubereitung>
      <Arbeitszeit>
        <Einheit>Einheit</Einheit>
      </Arbeitszeit>
      <Schwierigkeitsgrad>Schwierigkeitsgrad</Schwierigkeitsgrad>
      <Brennwert>
        <Einheit>Einheit</Einheit>
      </Brennwert>
      <Text>Text</Text>
    </Zubereitung>
    <Kommentare>
      <Titel>Titel</Titel>
      <Kommentar>
        <Nutzer>Nutzer</Nutzer>
        <Avatar>Avatar</Avatar>
        <Zeitstempel>
          <Tag>1</Tag>
          <Monat>1</Monat>
          <Jahr>2001</Jahr>
        </Zeitstempel>
        <Text>Text</Text>
        <Hilfreich>Hilfreich</Hilfreich>
      </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>
